AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'lib/valkey/protobuf/**/*.rb'

Style/StringLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

