AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'lib/valkey/protobuf/**/*.rb'

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Lint/RescueException:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false # false positives

Style/StringLiterals:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ElseAlignment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'test/**/*'

Bundler/OrderedGems:
  Enabled: false

