name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} Valkey ${{ matrix.valkey }}
    strategy:
      matrix:
        ruby:
          - 3.3.7
        valkey:
          - 7.0
          - 7.2.9
          - 8

    services:
      valkey:
        image: valkey/valkey:8
        ports:
          - 6379:6379
        options: >-
          --health-cmd="valkey-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rubocop
        run: bundle exec rake rubocop
      - name: tests
        run: bundle exec rake test

